In [1]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [2]:
steps = [('StandardScaler', StandardScaler()),
         ('classifier', LogisticRegression())]

In [3]:
steps

[('StandardScaler', StandardScaler()), ('classifier', LogisticRegression())]

In [4]:
pipe = Pipeline(steps)

In [5]:
from sklearn import set_config

In [6]:
set_config(display='diagram')

In [7]:
pipe

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [8]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000)

In [9]:
X.shape

(1000, 20)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_train

array([[-0.51309854, -1.62861469,  0.11674141, ..., -0.95843516,
        -1.30049802,  0.50996782],
       [-0.72861476,  1.11402085, -0.6109657 , ...,  0.90953843,
        -0.04129704, -1.36683335],
       [-1.2534168 ,  0.88203858,  0.85250245, ...,  0.89767109,
         0.85092897, -1.05630996],
       ...,
       [ 1.42959388, -0.37885279,  0.53802264, ...,  2.18300281,
        -0.25284885,  0.23590622],
       [ 0.27207493,  0.79382056, -1.82067271, ..., -0.1304661 ,
        -0.13312563, -2.19003378],
       [ 0.58476276, -0.32202978, -0.71563754, ...,  0.79006224,
        -0.02174823, -1.17060261]], shape=(670, 20))

In [12]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [13]:
y_pred = pipe.predict(X_test)

In [14]:
y_pred

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,

In [15]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [16]:
steps = [
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=2)),
    ('SVC', SVC())]

In [17]:
pipe2 = Pipeline(steps)

In [18]:
pipe2.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('SVC', SVC())])

In [19]:
pipe2.predict(X_test)

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,

In [20]:
from sklearn.impute import SimpleImputer

In [21]:
import numpy as np
numeric_processor = Pipeline(steps=[
    ('imputation_mean', SimpleImputer(missing_values=np.nan,strategy='mean')),
    ('scaler', StandardScaler())
])

In [22]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [23]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor = Pipeline(steps=[{"imputation_constant", SimpleImputer(fill_value='missing',strategy='constant')},
                                        ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [24]:
categorical_processor

Pipeline(steps=[{SimpleImputer(fill_value='missing', strategy='constant'),
                 'imputation_constant'},
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [25]:
from sklearn.compose import ColumnTransformer

In [26]:
preprocessor = ColumnTransformer(
    transformers=[[("categorical", categorical_processor, ['gender', 'City']),
                   ("numerical", numeric_processor, ['Age', 'Height'])
                   ]])
preprocessor

ColumnTransformer(transformers=[[('categorical',
                                  Pipeline(steps=[{SimpleImputer(fill_value='missing',
                                                                 strategy='constant'),
                                                   'imputation_constant'},
                                                  ('onehot',
                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                  ['gender', 'City']),
                                 ('numerical',
                                  Pipeline(steps=[('imputation_mean',
                                                   SimpleImputer()),
                                                  ('scaler',
                                                   StandardScaler())]),
                                  ['Age', 'Height'])]])

In [27]:
from sklearn.pipeline import make_pipeline

In [28]:
pipe = make_pipeline(preprocessor, LogisticRegression())

In [29]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[[('categorical',
                                                   Pipeline(steps=[{SimpleImputer(fill_value='missing',
                                                                                  strategy='constant'),
                                                                    'imputation_constant'},
                                                                   ('onehot',
                                                                    OneHotEncoder(handle_unknown='ignore'))]),
                                                   ['gender', 'City']),
                                                  ('numerical',
                                                   Pipeline(steps=[('imputation_mean',
                                                                    SimpleImputer()),
                                                                   ('scaler',
                                                                    StandardScaler())]),
                                                   ['Age', 'Height'])]])),
                ('logisticregression', LogisticRegression())])